# wrangler.toml

name = "andaman-travel-worker"


compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ] 


main = ".open-next/worker.js"

# Configuration for serving static assets via the Worker
[assets]
binding = "ASSETS" 
directory = ".open-next/assets" 


[[d1_databases]]
binding = "DB" 
database_name = "database" 
database_id = "96ed6730-6597-4715-85b0-7408ac403d31" 

# Optional: Add R2 binding if using Next.js Incremental Cache with R2
# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET" # Standard binding name expected by OpenNext for R2 cache
# bucket_name = "your-r2-bucket-name-for-caching" # Replace with your actual R2 bucket name

# Optional: Add self-reference service binding if needing ISR/On-Demand Revalidation
# [[services]]
# binding = "WORKER_SELF_REFERENCE" # Standard binding name expected by OpenNext
# service = "andaman-travel-worker" # MUST match the top-level 'name'

# Add other bindings (KV, Queues, Environment Variables) as needed
# [vars]
# MY_ENV_VAR = "some_value"
